baseURL = "https://www.yuzhuohui.info/"
languageCode = "zn-CN"
defaultContentLanguage = "en"
title = "小於的宅基地"                         # site title  # 网站标题
theme = ["hugo-video", "LoveIt"]
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
defaultTheme = "auto"

staticDir = "static"

[author]
  name = "小於"
  email = "agassi21@gmail.com"
  link = "https://twitter.com/Agassi_yzh"

[params]
  # LoveIt theme version
  version = "0.2.X"
  [params.page]
    [params.page.comment]
      enable = true
      [params.page.comment.disqus]
        enable = true
        shortname = 'iamagassi'
  [params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = "UA-13148173-4"
      # 是否匿名化用户 IP
      anonymizeIP = true


[markup]
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "文章"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3

